### ISSUE TITLE
PHP 7.1 Compatibility Errors 

### ISSUE THREAD

**Issue by brianjking** [littlebizzy/disable-cart-fragments#1]
While using the [SiteGround Optimizer](https://wordpress.org/support/plugin/sg-cachepress/) to check for PHP 7.1 compatibility it found the following errors in the Disable Cart Fragments plugin

```
FILE: /home/robotbea/public_html/wp-content/plugins/disable-cart-fragments-littlebizzy/admin-notices-ms.php
-----------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------------------------
 85 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
 86 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
-----------------------------------------------------------------------------------------------------------
```

**Comment by lukecav** [comment]
https://github.com/lukecav/disable-cart-fragments/commit/58f515aaf54f301eeb8e92954629349322d931a8

**Comment by jessuppi** [comment]
Okay thank you, will incorporate a patch into version 1.1.0 asap

**Comment by lukecav** [comment]
@jessuppi 

Any ETA on when the 1.1.0 update will be on the WP repo?

**Comment by jessuppi** [comment]
Should be ready within the next several days, we've tested on PHP 7.2 and not causing any fatal errors so doesn't seem to be an emergency. That said, next version will fully convert to namespaces and overall better code structure as we've been doing with other plugins. Thanks!

**Comment by jessuppi** [comment]
Tested with PHP 7.0, PHP 7.1, PHP 7.2 and several popular plugins:

https://github.com/littlebizzy/disable-cart-fragments/tree/1.1.0
